#!/bin/sh

. ./lib/categoryselect
f1(){
    ___x_cmd_ui_categoryselect ___x_cmd_ui_categoryselect_test_func_ls
    echo "___X_CMD_UI_CATEGORYSELECT_FINAL_COMMAND:" "$___X_CMD_UI_CATEGORYSELECT_FINAL_COMMAND"
    echo "___X_CMD_UI_CATEGORYSELECT_CURRENT_ITEM:" "$___X_CMD_UI_CATEGORYSELECT_CURRENT_ITEM"
}

f2(){
    ___x_cmd_ui_categoryselect ___x_cmd_ui_categoryselect_test_func_env
    echo "___X_CMD_UI_CATEGORYSELECT_FINAL_COMMAND:" "$___X_CMD_UI_CATEGORYSELECT_FINAL_COMMAND"
    echo "___X_CMD_UI_CATEGORYSELECT_CURRENT_ITEM:" "$___X_CMD_UI_CATEGORYSELECT_CURRENT_ITEM"
}

f1
