#! /bin/sh

xrc assert

x proxy go set
assert_stdout "___x_cmd_proxy_go_get" <<A
GOPROXY="https://goproxy.cn,direct"
A

# go get github.com/opencontainers/runc
x proxy go unset
assert_stdout "___x_cmd_proxy_go_get" <<A
GOPROXY="https://proxy.golang.org,direct"
A
