#! /bin/sh

xrc assert

x proxy go set
assert_stdout "go env | grep -i GOPROXY" <<A
GOPROXY="https://goproxy.cn,direct"
A

# go get github.com/opencontainers/runc
x proxy go unset
assert_stdout "go env | grep -i GOPROXY" <<A
GOPROXY="https://proxy.golang.org,direct"
A
