#! /bin/bash

test_proxy_apk(){
    . ~/.x-cmd/xrc/latest
    . ./testcase/v0_test
    
    proxy_log info "Testing proxy apk replace to install curl"
    x proxy apk replace
    apk add curl

    proxy_log info "Testing proxy apk rollback to install vim"
    x proxy apk rollback
    apk add vim
}

test_cross_env() {
    # $(seq 11 14)
    for i in 11 12 13 14 ; do
        proxy_log info "Testing : 3.$i"
        docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd alpine:3."${i}" \
            sh -c "cd pd && . ./testcase/v0_test_apk && \
            test_proxy_apk"
    done

    proxy_log info "Testing : alpine"
    docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd xcmd/alpine-dev \
        sh -c "cd pd && . ./testcase/v0_test_apk && \
        test_proxy_apk"
}