#! /bin/sh

cp -r ./* ~/.x-cmd/proxy/

xrc assert
x log proxy
xrc proxy

if [ -n "${BASH_VERSION}${ZSH_VERSION}" ]; then
    xrc advise/v0
    advise rm proxy
    proxy_log "advise proxy time: "
    time advise proxy
fi

# Section: Test functions

test_proxy_advise_json() {
  assert_stdout "advise cat proxy" <<A
{
  "set": null,
  "unset": null,
  "version": null,
  "pip": {
    "url": {
      "qinghua|qh|tsinghua|tuna": null,
      "ustc": null,
      "aliyun": null,
      "huazhong": null,
      "douban": null,
      "tencent|qq|weixin": null
    },
    "get": {
    },
    "set": {
      "qinghua|qh|tsinghua|tuna": null,
      "ustc": null,
      "aliyun": null,
      "huazhong": null,
      "douban": null,
      "tencent|qq|weixin": null
    },
    "unset": {
    }
  },
  "npm": {
    "url": {
      "aliyun|ali": null,
      "official": null
    },
    "set": {
      "aliyun|ali": null,
      "official": null
    },
    "get": {
    },
    "unset": {
    }
  },
  "maven": null,
  "go": {
    "get": {
    },
    "auto": {
    },
    "unset": {
    },
    "gosumdb": {
      "set": {
      },
      "unset": {
      }
    },
    "set": {
      "aliyun|ali": null,
      "goproxy|goproxy": null,
      "qiniu|io|goproxy": null,
      "official": null
    },
    "service": {
    },
    "tutorial": {
    }
  },
  "gem": {
    "url": {
      "ruby-china|cn": null,
      "official": null
    },
    "set": {
      "ruby-china|cn": null,
      "official": null
    },
    "get": {
    },
    "unset": {
    }
  },
  "cargo": {
    "url": {
      "tuna": null,
      "sjtu": null,
      "rustcc": null
    },
    "get": {
    },
    "replace|set": {
      "tuna": null,
      "sjtu": null
    },
    "rollback": {
      "#1": "x proxy cargo rollback ls",
      "ls": {
      }
    }
  },
  "apt": {
    "url": {
      "ali": null,
      "tuna": null
    },
    "replace|set": {
      "ali": null,
      "tuna": null
    },
    "rollback": {
      "#1": "x proxy apt rollback ls",
      "ls": null
    }
  },
  "yum": {
    "url": {
      "ustc": null,
      "tuna": null,
      "official": null
    },
    "rollback|unset": {
      "#1": "x proxy yum rollback ls",
      "ls": {
      }
    },
    "replace": {
      "ustc": null,
      "tuna": null,
      "official": null
    }
  },
  "brew": {
    "url": {
      "tuna|tsinghua|qh": null,
      "aliyun|ali": null,
      "tencent": null,
      "bfsu": null,
      "ustc": null,
      "custom": null
    },
    "get": {
    },
    "set": {
      "--verbose|-v": null,
      "bfsu": null,
      "tuna|tsinghua|qh": null,
      "tencent": null,
      "aliyun|ali": null,
      "ustc": null,
      "custom": null
    },
    "unset": {
      "--verbose|-v": null
    }
  },
  "apk": {
    "url": {
      "ustc": null,
      "official": null
    },
    "replace|set": {
      "ustc": null,
      "official": null
    },
    "rollback": {
      "#1": "x proxy apk rollback ls",
      "ls": {
      }
    }
  }
}
A
}

# EndSection

# Section: Run test

if [ -n "${BASH_VERSION}${ZSH_VERSION}" ]; then
    test_proxy_advise_json
fi

case $1 in
    apt|apk|yum)
        . ./testcase/v0_test_"${1}"
        test_cross_env
        ;;
    go|brew|gem|cargo|npm|pip|maven)
        . ./testcase/v0_test_"${1}"
        ;;  
    base)
        ;;
    *)
        printf "Usage: x test {brew|apt|yum|apk|npm|pip|gem|cargo|go|maven|base}"
        exit 1
        ;;
esac

# EndSection