#! /bin/sh

xrc assert

x proxy pip set
pip3 install pandoc > /dev/null
pip3 uninstall -y pandoc > /dev/null
pip config get global.index-url

assert_stdout "pip config get global.index-url 2>&1" <<A
https://pypi.mirrors.ustc.edu.cn/simple/
A

# # go get github.com/opencontainers/runc
x proxy pip unset
pip3 install pandoc > /dev/null
pip3 uninstall -y pandoc > /dev/null

assert_stdout "pip config get global.index-url 2>&1" <<A
ERROR: No such key - global.index-url
A