#! /bin/sh

test_proxy_pacman(){
    . ~/.x-cmd/xrc/latest
    . ./testcase/v0_test
    
    proxy_log info "Testing proxy pacman replace to install curl"
    x proxy pacman replace
    pacman -S --noconfirm curl

    proxy_log info "Testing proxy pacman rollback to install vim"
    x proxy pacman rollback
    pacman -S --noconfirm vim
}

test_cross_env() {
    docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd archlinux \
        bash -c "cd pd && . ./testcase/v0_test_pacman && \
        test_proxy_pacman"
}

dbash() {
    docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd archlinux \
        bash -c "printf \". ~/.x-cmd/xrc/latest\" >/root/.bashrc && cd pd && bash"
}