#! /bin/sh

xrc assert

x proxy npm set

assert_stdout "x proxy npm get" <<A
https://registry.npm.taobao.org/
A

assert_stdout "x proxy npm url ali" <<A
https://registry.npm.taobao.org/
A

x proxy npm unset

assert_stdout "x proxy npm get" <<A
https://registry.npmjs.org/
A