#! /bin/sh
x log init proxy
x log proxy
xrc proxy

test_run() {
    proxy_log info "Testing apt replace: "
    x proxy apt replace

    proxy_log info "Testing apt update: "
    apt-get update
    apt-get install -y curl

    proxy_log info "Testing apt rollback: "
    x proxy apt rollback

    proxy_log info "Testing apt update: "
    apt-get update
    apt-get install -y nano
}

test_cross_env(){
    # for i in sid testing bullseye buster stretch jessie ; do
    #     proxy_log info "Testing : " "debian:$i"
    #     docker run --rm -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd debian:"${i}" sh -c ". ~/.x-cmd/xrc/latest && cd pd && . ./testcase/v0_test_apt && test_run"
    #     proxy_log info "Testing : " "amd64/debian:$i"
    #     docker run --rm -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd amd64/debian:"${i}" sh -c ". ~/.x-cmd/xrc/latest && cd pd && . ./testcase/v0_test_apt && test_run"
    # done

    # # TODO: There is some problem in ubuntu:12.04
    # for i in $(seq -w 14 2 21); do
    #     proxy_log info "Testing : " "ubuntu:$i.04"
    #     docker run --rm -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd ubuntu:"${i}".04 sh -c ". ~/.x-cmd/xrc/latest && cd pd && . ./testcase/v0_test_apt && test_run"
    #     proxy_log info "Testing : " "amd64/ubuntu:$i.04"
    #     docker run --rm -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd amd64/ubuntu:"${i}".04 sh -c ". ~/.x-cmd/xrc/latest && cd pd && . ./testcase/v0_test_apt && test_run"
    # done

    for i in debian ubuntu ; do
        proxy_log info "Testing : " "$i"
        docker run --rm -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd xcmd/base-"${i}"-2-dev sh -c ". ~/.x-cmd/xrc/latest && cd pd && . ./testcase/v0_test_apt && test_run"
    done
}
