#! /bin/sh

## if have deno command, then remove deno
if command -v deno >/dev/null 2>&1; then
    deno --version | grep "deno"
    brew uninstall deno && brew cleanup -s
else
    proxy_log "no deno command"
fi

test_proxy_brew() {

    x proxy brew set -v
    time brew install deno

    # If you were slow to brew unset, you can use your own proxy
    # export all_proxy=socks5://127.0.0.1:1080
    x proxy brew unset -v
    brew uninstall deno && brew cleanup -s
    time brew install deno
}

test_proxy_brew
brew uninstall deno && brew cleanup -s