#! /bin/sh

test_proxy_dnf(){
    . ~/.x-cmd/xrc/latest
    . ./testcase/v0_test
    
    proxy_log info "Testing proxy dnf replace to install curl"
    x proxy dnf replace
    dnf install -y curl

    proxy_log info "Testing proxy dnf rollback to install vim"
    x proxy dnf rollback
    dnf install -y vim
}

test_cross_env() {
    # proxy_log info "Testing : centos:8"
    # docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd centos:"8" \
    #     sh -c "cd pd && . ./testcase/v0_test_dnf && \
    #     test_proxy_dnf"

    proxy_log info "Testing : xcmd/base-centos-2-dev"
    docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd xcmd/base-centos-2-dev \
        sh -c "cd pd && . ./testcase/v0_test_dnf && \
        test_proxy_dnf"
}

dbash() {
    docker run -it -v  ~/.x-cmd/:/root/.x-cmd/ -v "$(pwd)":/pd centos \
        bash -c "printf \". ~/.x-cmd/xrc/latest\" >/root/.bashrc && cd pd && bash"
}