#! /usr/bin/env bash

git remote remove gitee 2>/dev/null
git remote add gitee git@gitee.com:x-bash/ps1env.git
git push gitee main

git remote remove github 2>/dev/null
git remote add github git@github.com:x-bash/ps1env.git
git push github main
