#! /usr/bin/env sh

f1(){
    cat ./.x-cmd/dev/testcase/test.txt | awk \
    -f "./.x-cmd/dev/testcase/wcwidth.awk" \
    -f "./.x-cmd/dev/testcase/aaa.awk"
}
# time f1
f1

# time . ./.x-cmd/dev/testcase/testutf-8

# test.txt                                            100K 的中文文档
# wcswdith($0)
# windows busybox                                     0.31s
# ubuntu gawk                                         0.014s
# git bash                                            0.049s
# docker run -it -v "$(pwd)":/ui "xcmd/alpine-dev"    15.18s
# docker run -it -v "$(pwd)":/ui "xcmd/debian-dev"    0.024s