#!/bin/sh

. ./lib/app/catsel
. ./lib/app/lsenv
f1(){
    ___x_cmd_ui_catsel
    echo "___X_CMD_UI_CATSEL_FINAL_COMMAND:" "$___X_CMD_UI_CATSEL_FINAL_COMMAND"
    echo "___X_CMD_UI_CATSEL_CURRENT_ITEM:" "$___X_CMD_UI_CATSEL_CURRENT_ITEM"
}


f2(){
    ___x_cmd_ui_lsenv
    echo "___X_CMD_UI_LSENV_FINAL_COMMAND:" "$___X_CMD_UI_LSENV_FINAL_COMMAND"
    echo "___X_CMD_UI_LSENV_CURRENT_ITEM:" "$___X_CMD_UI_LSENV_CURRENT_ITEM"
}

f1
