#!/bin/sh

. ./lib/truefalse
xrc ui
___x_cmd_ui_tf "false" "Sorry, your..."
___x_cmd_ui_tf "" "Type, dddddd..."
___x_cmd_ui_tf "true" "Created, repository Markdown is 123456 light \n weight and easy-to-use syntax for styling all forms of writing on the GitHub platform."

ui tf "false" "Creating repo success" "repo_id:202213232" "url:url" "repo_owner:repo_owner"

