#! /usr/bin/env bash

mod_list="
xrc
x-cmd
hub
install

# basic modules: non dependency
str
list
dict
assert
json

# basic modules: dependencies
param
http
advise
ui

# modules
static-build
ccmd
xdk
zuz
el

# Apps
tldr
proxy
theme

# web clients
ali
gitee
"

WSROOT="${BASH_SOURCE[0]}"

if [ "${WSROOT#/}" = "$WSROOT" ]; then
    WSROOT="$(pwd)/${BASH_SOURCE[0]}"
fi

# printf "%s\n" "$WSROOT"

WSROOT="${WSROOT%/.x-cmd/*}"

all_ls()(
    cd "$WSROOT/mod" && \
    while read -r line; do
        [ "${line#\#}" != "$line" ] && continue
        [ "$line" = "" ] && continue
        for i in $line/latest $line/v* $line/_v*/* $line/_v*/**/*; do
            [[ "$i" == *_test* ]] && continue
            [ -f "$i" ] && printf "%s\n" "$i"
        done
    done 2>/dev/null <<<"$mod_list"
)

all_wc()(
    cd "$WSROOT/mod" &&
        all_ls | xargs wc
)

all_tar()(
    cd "$WSROOT/mod" &&
    mkdir -p "$WSROOT/dist" &&
        eval "tar cvf all.tar $(all_ls | tr '\n' ' ')" &&
        mv all.tar "$WSROOT/dist/all.tar" &&
        ls -alh "$WSROOT/dist/all.tar"
)

all_tgz()(
    cd "$WSROOT/mod" &&
    mkdir -p "$WSROOT/dist" &&
        eval "tar czvf all.tgz $(all_ls | tr '\n' ' ')" &&
        mv all.tgz "$WSROOT/dist/all.tgz" &&
        ls -alh "$WSROOT/dist/all.tgz"
)

# all_7z(){
#     cd "$WSROOT/mod" && \
#         mkdir -p dist \
#         eval "7z a $WSROOT/dist/all.tar.7z $(all_ls | tr '\n' ' ')" \
#         ls -alh dist/all.tar.7z
# }

if [ "$#" -gt 0 ]; then
    op="$1"
    shift
    "all_$op" "$@"
fi

