#! /usr/bin/env bash

add(){
    local name="${1:?Provide module name}"
    # local position="${2:-"git@gitee.com/x-bash/$name.git"}"
    local position="${2:-"https://gitee.com/x-bash/$name.git"}"
    local branch="${3:-main}"
    git subtree add --prefix="mod/$name" "$position" "$branch" --squash
}

pull(){
    local name="${1:?Provide module name}"
    # local position="${2:-"git@gitee.com/x-bash/$name.git"}"
    local position="${2:-"https://gitee.com/x-bash/$name.git"}"
    local branch="${3:-main}"
    git subtree pull --prefix="mod/$name" "$position" "$branch" --squash
}

update(){
    local IFS
    local mod
    git prune
    while read -r mod; do
        if [ -e "mod/$mod" ]; then
            pull "$mod"
        else
            add "$mod"
        fi
    done <<A
$(ls)
A
}

if [ "$#" -gt 0 ]; then
    op="$1"; shift

    case "$op" in
        add)        add "$@" ;;
        pull)       pull "$@" ;;
        all|*)      update "$@" ;;
    esac
fi
