#! /usr/bin/env bash

git remote remove gitee 2>/dev/null
git remote add gitee git@gitee.com:x-cmd/x-cmd.git
git push gitee

git remote remove github 2>/dev/null
git remote add github git@github.com:x-cmd/x-cmd.git
git push github
