#! /usr/bin/env bash
. "$HOME/.x-cmd/boot" 2>/dev/null || eval "$(curl https://get.x-cmd.com)"

# args
BASE_DIR=$(pwd $(dirname ${BASH_SOURCE[0]})/../)
source $BASE_DIR/v0
TEST_DATA=$(cat "$BASE_DIR/test.json")

owner='{
        name: Edwin.Junhao.Lee,
        email: edwin.jh.lee@gmail.com,
        email1: 909xxxxxx@qq.com
        email2: 11111
        isMe: false
        isYou: true
        isHer: null
    }'
developer="{
        Owner: $owner,
        Contributors: [
            Tang Zhiwen,
            Li Tinghui,
            1390296043900,
            null
        ]
    }"
# functions
debug() {
  LOG=$1
  echo -e $(tput setaf 3)"📝 INFO: \c" $(tput sgr0)
  echo -e $(tput setaf 6)"$LOG" $(tput sgr0)
}

function ui_test_module_line() {
    echo -e "\033[1;33m ------- ✅ $1 ❌ ------- \033[0m"
}

function test_color() {
    ui_test_module_line "test_color"
    local testData=$1
    json_color $testData
    json color developer
    json col $testData
    json c $testData
}

function test_var() {
    ui_test_module_line "test_var"
    owner='{
        name: Edwin.Junhao.Lee,
        email: edwin.jh.lee@gmail.com,
        email1: 909xxxxxx@qq.com,
        email2: 11111,
        isMe: false,
        isYou: true,
        isHer: null
    }'
    developer="{
        Owner: $owner,
        Contributors: [
            Tang Zhiwen,
            Li Tinghui,
            1390296043900,
            null
        ]
    }"
    json var eeee $developer
    json_var aaaa $1
    json color eeee
    json_color aaaa
}

function test_append() {
    ui_test_module_line "test_append"
    local testData=$1
    local appendData=$2
    json_push $testData $appendData
    json_append $testData $appendData
    json_color ${testData%%.*}

    json push developer.Contributors "32323"
    json append developer.Contributors [1,2,3,"aaaa12312"]
    json c developer
}

function test_unshift() {
    ui_test_module_line "test_unshift"
    local targetData=$1
    local unshiftData=$2

    json_unshift $targetData $unshiftData
    json_prepend $targetData $unshiftData
    json_color ${1%%.*}

    json unshift developer.Contributors "front1"
    json prepend developer.Contributors "front2"
    json col developer
}

function test_keys() {
    ui_test_module_line "test_keys"
    local testData=$1
    json_keys $testData
    echo '-------------------'
    json k $testData
    echo '-------------------'
    json key developer
}

function test_values() {
    ui_test_module_line "test_values"
    local testData=$1
    # json_values $testData
    echo '-------------------'
    json values developer.Owner
}

function test_shift() {
    ui_test_module_line "test_shift"
    local testData=$1
    json_shift $testData
    json color ${testData%%.*}

    json sh developer.Contributors
    json col developer
}

function test_pop() {
    ui_test_module_line "test_pop"
    local testData=$1
    json_pop $testData
    json_color ${testData%%.*}
    json po developer.Contributors
    json col developer
}

function test_length() {
    ui_test_module_line "test_length"
    local testData=$1
    length=$(json_length $testData)
    echo length: $length

    length=$(json len developer.Contributors)
    echo length: $length
}

function test_put() {
    ui_test_module_line "test_put"
    local testData=$1
    local putData=$2
    json_put $testData $putData
    json_color ${testData%%.*}

    json put developer.Owner.name "qbenben"
    json c developer
}

function test_del() {
    ui_test_module_line "test_del"
    local delData=$1

    json_del $delData
    json_color ${delData%%.*}

    json d developer.Owner.name
    json c developer
}

function test_query() {
    ui_test_module_line "test_query"
    local testData=$1
    local queryData=$1
    local query=$(json_query $queryData)
    echo $query

    json q developer.Owner.email
}

# run main script
test_color TEST_DATA
test_var "$TEST_DATA"
test_append TEST_DATA.you "hehehaha"
test_unshift TEST_DATA.you "wqwqwqwqwq"
test_keys TEST_DATA
test_values TEST_DATA
test_shift TEST_DATA.you
test_pop TEST_DATA.you
test_length TEST_DATA.you
test_put TEST_DATA.name "aaaa"
test_del TEST_DATA.name
test_query TEST_DATA.email




