#!/bin/bash

# gen 10000 number and print it
x log init advise

for num in 100 1000 10000 100000 ; do
    rm -rf "${TMPDIR%/}"/.x-cmd/advise_auto_json
    mkdir -p "${TMPDIR%/}"/.x-cmd/advise_auto_json
    advise_log info "Generating $num advise json"
    for i in $(seq 1 $num); do
        printf "{ \"hello\": null }" > "${TMPDIR%/}/.x-cmd/advise_auto_json/test1$i"
    done
    time (advise load)
done

rm -rf "${TMPDIR%/}"/.x-cmd/advise_auto_json
mkdir -p "${TMPDIR%/}"/.x-cmd/advise_auto_json
